source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# CocoaPods 1.16.2 pulls in xcodeproj >= 1.27.0 (fixes PBXFileSystemSynchronizedRootGroup)
gem 'cocoapods', '>= 1.16.2', '!= 1.15.0', '!= 1.15.1'
gem 'xcodeproj', '>= 1.27.0', '< 2.0'

# Keep your original activesupport constraint
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'

# Keep if you had a known issue >= 1.3.4; otherwise you can delete this line
gem 'concurrent-ruby', '< 1.3.4'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
